# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AHBExchangeRate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AHBExchangeRate

  target 'AHBExchangeRateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AHBExchangeRateUITests' do
    # Pods for testing
  end

end
